# Generated by Django 5.2 on 2025-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Etc/GMT-0', max_length=50),
        ),
    ]
