# Generated by Django 5.2 on 2025-05-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='old_cart',
        ),
    ]
