# Generated by Django 5.2 on 2026-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='platfomr',
            new_name='country',
        ),
        migrations.AddField(
            model_name='guest',
            name='platform',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
