# Generated by Django 5.2 on 2026-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_rename_platfomr_guest_country_guest_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('warning_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='terms_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
