# Generated by Django 5.2 on 2026-03-27 07:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_term_guest_terms_answers_alter_guest_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='selfie',
            field=cloudinary.models.CloudinaryField(default='default.jpy', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
