# Generated by Django 5.2 on 2026-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_guest_selfie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='question',
        ),
        migrations.AddField(
            model_name='term',
            name='question_en',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='question_th',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='term',
            name='question_zh',
            field=models.TextField(blank=True),
        ),
    ]
