# Generated by Django 5.2 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_term_question_term_question_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='warning_message',
            new_name='warning_message_en',
        ),
        migrations.AddField(
            model_name='term',
            name='warning_message_th',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='term',
            name='warning_message_zh',
            field=models.TextField(blank=True),
        ),
    ]
