# Generated by Django 5.2 on 2026-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_rename_warning_message_term_warning_message_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('out', models.BooleanField(default=False)),
                ('key', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
            ],
        ),
    ]
