# Generated by Django 5.2 on 2026-04-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_roomstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstate',
            old_name='clean',
            new_name='is_clean',
        ),
    ]
