# Generated by Django 5.2 on 2026-04-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_rename_clean_roomstate_is_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='end_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='hostel.roomstate'),
        ),
        migrations.AddField(
            model_name='guest',
            name='start_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
