# Generated by Django 5.2 on 2026-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_guest_end_day_guest_room_guest_start_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterm', models.CharField(max_length=30)),
            ],
        ),
    ]
