# Generated by Django 5.2 on 2026-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='iterm',
        ),
        migrations.AddField(
            model_name='allergy',
            name='item_cn',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergy',
            name='item_en',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergy',
            name='item_th',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
