# Generated by Django 5.2 on 2026-05-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_monthlyjob_monthlyjobrecord_monthlyjobimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('birth_day', models.DateTimeField()),
                ('start_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffDayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('status', models.CharField(choices=[('work', 'Work'), ('half', 'Half Day'), ('off', 'Day Off')], default='work', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='hostel.staff')),
            ],
        ),
    ]
