# Generated by Django 5.2 on 2026-05-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_staff_staffdayrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_day',
            field=models.DateField(blank=True),
        ),
    ]
