# Generated by Django 5.2 on 2026-05-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_alter_staff_birth_day_alter_staff_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
