# Generated by Django 5.2 on 2025-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_date', models.CharField(blank=True, max_length=255, null=True)),
                ('type_sl', models.CharField(max_length=255)),
                ('percent_sl', models.CharField(max_length=255)),
                ('type_pr', models.CharField(max_length=255)),
                ('percent_pr', models.CharField(max_length=255)),
                ('type_un', models.CharField(max_length=255)),
                ('percent_un', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
