# Generated by Django 5.2 on 2025-06-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='end2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
