# Generated by Django 5.2 on 2025-06-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0002_timerecord_end2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='end2',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='tag',
        ),
    ]
