# Generated by Django 5.2 on 2025-06-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0003_remove_timerecord_duration_remove_timerecord_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerecord',
            name='end',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerecord',
            name='end2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
