# Generated by Django 5.2 on 2025-06-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0005_remove_timerecord_end2_timerecord_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerecord',
            old_name='flow',
            new_name='end2',
        ),
    ]
