# Generated by Django 5.2 on 2025-06-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0006_rename_flow_timerecord_end2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='end2',
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
