# Generated by Django 5.2 on 2025-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0008_alter_timerecord_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReport2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7)),
                ('total_duration', models.IntegerField(default=0)),
                ('type_data', models.JSONField(default=dict)),
                ('tag_data', models.JSONField(default=dict)),
            ],
        ),
    ]
