# Generated by Django 5.2 on 2025-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0009_timereport2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeReport2',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='percent_pr',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='percent_sl',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='percent_un',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='type_pr',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='type_sl',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='type_un',
        ),
        migrations.RemoveField(
            model_name='timereport',
            name='year_date',
        ),
        migrations.AddField(
            model_name='timereport',
            name='tag_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='timereport',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timereport',
            name='type_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='timereport',
            name='year_month',
            field=models.CharField(default='2025-01', max_length=7),
            preserve_default=False,
        ),
    ]
