# Generated by Django 5.2 on 2025-06-25 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0011_timerecord_user_timereport_user_timetag_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timereport',
            unique_together={('user', 'year_month')},
        ),
    ]
