# Generated by Django 5.2 on 2025-07-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0012_alter_timereport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereport',
            name='day_data',
            field=models.JSONField(default=dict),
        ),
    ]
