# Generated by Django 5.2 on 2025-07-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_sys', '0016_rename_tag_healthmedicinetag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='medicine',
            field=models.JSONField(default=list),
        ),
    ]
